Install jest-dom types to work around build error
Here's the installation:

    $ yarn add "@types/testing-library__jest-dom"
    ➤ YN0000: ┌ Resolution step
    ➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [72bc7] doesn't provide @babel/plugin-syntax-flow (p1d224), requested by eslint-plugin-flowtype
    ➤ YN0002: │ eslint-config-react-app@npm:7.0.1 [72bc7] doesn't provide @babel/plugin-transform-react-jsx (pcfaf0), requested by eslint-plugin-flowtype
    ➤ YN0002: │ pnp-ts-solver@workspace:. doesn't provide @testing-library/dom (p3bf33), requested by @testing-library/user-event
    ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
    ➤ YN0000: └ Completed in 0s 316ms
    ➤ YN0000: ┌ Fetch step
    ➤ YN0000: └ Completed in 0s 509ms
    ➤ YN0000: ┌ Link step
    ➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
    ➤ YN0000: └ Completed in 0s 204ms
    ➤ YN0000: Done with warnings in 1s 213ms

Here's the error that would appear on yarn start before this commit:

        Compiled successfully!

        You can now view pnp-ts-solver in the browser.

          Local:            http://localhost:3000
          On Your Network:  http://172.17.0.2:3000

        Note that the development build is not optimized.
        To create a production build, use yarn build.

        webpack compiled successfully
        ERROR in src/App.test.tsx:8:23
        TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.
             6 |   render(<App />);
             7 |   const linkElement = screen.getByText(/learn react/i);
          >  8 |   expect(linkElement).toBeInTheDocument();
               |                       ^^^^^^^^^^^^^^^^^
             9 | });
            10 |

        ^C%

There was no type error from yarn test; only from yarn start. None of
the other work-arounds I found online solved the issue.